[general]
service = "greetd-spawn"

[terminal]
vt = 1

[default_session]
command = "tuigreet --time --time-format '%A, %d %B %Y - %r' --user-menu --greeting 'Select User' --remember --remember-session --asterisks --power-shutdown 'systemctl poweroff' --power-reboot 'systemctl reboot' --power-no-setsid --width 140 --cmd niri-session"
user = "greetd"
